### ISSUE TITLE
can we just use private keyword?

### ISSUE THREAD

**Issue by zh99998** [tc39/proposal-private-fields#92] opened 2017-06-13 03:05 UTC
`#` is very ugly.. and looks like comment, may confused
`#` for comment is widely use in many language including coffeescript.

**Comment by bakkot** [comment] 2017-06-13 03:10
Duplicate of https://github.com/tc39/proposal-private-fields/issues/14.

See [the FAQ](https://github.com/tc39/proposal-private-fields/blob/master/FAQ.md#why-arent-declarations-private-x).

**Closed as completed** 2017-06-13 05:16 UTC
